"files": [
  {
    "source":"/source/**/*en_us.*",
    "translation":"/translations/%locale_with_underscore%/**/%locale_with_underscore%%original_file_name%",
    "translation_replace":{
      "en_us":""
    }
  },
  {
    "source": "/source/manifest.php",
    "translation": "/translations/%locale_with_underscore%/**/manifest.php",
  }
]
